export default {
  'daxiaodanshuang-daxiaodanshuang-qianerdaxiaodanshuang': {},
  'daxiaodanshuang-daxiaodanshuang-houerdaxiaodanshuang': {},
  'yixing-dingweidan-fushi': {},
  'housan-zhixuan-fushi': {},
  'erxing-zhixuan-qianerfushi': {},
  'erxing-zhixuan-houerfushi': {},
  'erxing-zuxuan-houerfushi': {},
  'erxing-zuxuan-qianerfushi': {},
  'budingwei-sanxingbudingwei-housanyimabudingwei': {},
  'budingwei-sanxingbudingwei-housanermabudingwei': {},
  'erxing-zuxuan-qianerdanshi': {},
  'erxing-zuxuan-houerdanshi': {},
  'housan-zhixuan-danshi': {},
  'erxing-zhixuan-qianerdanshi': {},
  'erxing-zhixuan-houerdanshi': {},
  'housan-zuxuan-zusandanshi': {},
  'housan-zuxuan-zuliudanshi': {},
  'housan-zuxuan-hunhezuxuan': {},
  'housan-zhixuan-hezhi': {},
  'housan-zuxuan-hezhi': {},
  'housan-zuxuan-zusan': {},
  'housan-zuxuan-zuliu': {}
}
